theme: jekyll-theme-cayman
title: "Framewise WaveGAN: High Speed Adversarial Vocoder in Time Domain with Very Low Computational Complexity"
description: "Demo Samples"
github:
  is_project_page: false
